version: "3"

services:
  ubuntu:
    image: ubuntu:20.04
    container_name: ubuntu-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./ubuntu:/usr/src/app
    tty: true
